<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MarketTest\SampleTest'                => __DIR__ . '/tests/Market/SampleTest.php',
    'ModuleTest'                           => __DIR__ . '/tests/Market/ModuleTest.php',
    'Market\Framework\TestCase'            => __DIR__ . '/tests/Market/Framework/TestCase.php',
    'Market\Controller\IndexController'    => __DIR__ . '/src/Market/Controller/IndexController.php',
    'Market\Controller\ViewController'     => __DIR__ . '/src/Market/Controller/ViewController.php',
    'Market\Controller\TestController'     => __DIR__ . '/src/Market/Controller/TestController.php',
    'Market\Controller\PostController'     => __DIR__ . '/src/Market/Controller/PostController.php',
    'Market\Factory\PostControllerFactory' => __DIR__ . '/src/Market/Factory/PostControllerFactory.php',
    'Market\Factory\PostFormFactory'       => __DIR__ . '/src/Market/Factory/PostFormFactory.php',
    'Market\Module'                        => __DIR__ . '/Module.php',
);
