<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SearchTest\SampleTest'             => __DIR__ . '/src/tests/Market/SampleTest.php',
    'ModuleTest'                        => __DIR__ . '/src/tests/Market/ModuleTest.php',
    'Market\Framework\TestCase'         => __DIR__ . '/src/tests/Market/Framework/TestCase.php',
    'Market\Controller\IndexController' => __DIR__ . '/src/Market/Controller/IndexController.php',
    'Market\Controller\TestController'  => __DIR__ . '/src/Market/Controller/TestController.php',
    'Market\Module'                     => __DIR__ . '/Module.php',
);
